# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'su_connection_add.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(798, 422)
        Form.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("ooopic_1569555377.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.gridLayout_37 = QtGui.QGridLayout(Form)
        self.gridLayout_37.setObjectName(_fromUtf8("gridLayout_37"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(Form)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(Form)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.comboBox = QtGui.QComboBox(Form)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.label_52 = QtGui.QLabel(Form)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.gridLayout.addWidget(self.label_52, 2, 0, 1, 1)
        self.gridLayout_35 = QtGui.QGridLayout()
        self.gridLayout_35.setObjectName(_fromUtf8("gridLayout_35"))
        self.comboBox_2 = QtGui.QComboBox(Form)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.gridLayout_35.addWidget(self.comboBox_2, 0, 0, 1, 1)
        self.toolButton = QtGui.QToolButton(Form)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.gridLayout_35.addWidget(self.toolButton, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_35, 2, 1, 1, 1)
        self.label_53 = QtGui.QLabel(Form)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.gridLayout.addWidget(self.label_53, 2, 2, 1, 1)
        self.gridLayout_37.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label_24 = QtGui.QLabel(self.tab)
        self.label_24.setGeometry(QtCore.QRect(10, 179, 722, 16))
        self.label_24.setText(_fromUtf8(""))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.layoutWidget = QtGui.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 11, 722, 163))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_13 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_6.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_6.addWidget(self.label_12, 5, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_6.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_6.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_40 = QtGui.QLabel(self.layoutWidget)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_6.addWidget(self.label_40, 3, 0, 1, 1)
        self.label_49 = QtGui.QLabel(self.layoutWidget)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_6.addWidget(self.label_49, 4, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.toolButton_2 = QtGui.QToolButton(self.layoutWidget)
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.gridLayout_3.addWidget(self.toolButton_2, 0, 1, 1, 1)
        self.toolButton_3 = QtGui.QToolButton(self.layoutWidget)
        self.toolButton_3.setObjectName(_fromUtf8("toolButton_3"))
        self.gridLayout_3.addWidget(self.toolButton_3, 0, 2, 1, 1)
        self.lineEdit_5 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_5.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.gridLayout_3.addWidget(self.lineEdit_5, 0, 0, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 7)
        self.gridLayout_7.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.lineEdit_7 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_7.setText(_fromUtf8(""))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.gridLayout_7.addWidget(self.lineEdit_7, 4, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lineEdit_6 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_6.setText(_fromUtf8(""))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.gridLayout_4.addWidget(self.lineEdit_6, 0, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_4, 3, 0, 1, 1)
        self.lineEdit_4 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout_7.addWidget(self.lineEdit_4, 1, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lineEdit_2 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setText(_fromUtf8(""))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout_2.addWidget(self.lineEdit_2, 0, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 1, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout_2.addWidget(self.lineEdit_3, 0, 2, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 10)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.gridLayout_7.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.comboBox_3 = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.comboBox_3, 5, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_7, 0, 1, 1, 1)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_8.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_8.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.layoutWidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_8.addWidget(self.label_11, 2, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.layoutWidget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_8.addWidget(self.label_13, 5, 0, 1, 1)
        self.label_48 = QtGui.QLabel(self.layoutWidget)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_8.addWidget(self.label_48, 3, 0, 1, 1)
        self.label_50 = QtGui.QLabel(self.layoutWidget)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_8.addWidget(self.label_50, 4, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_8, 0, 2, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_20 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.gridLayout_16 = QtGui.QGridLayout()
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.gridLayout_19 = QtGui.QGridLayout()
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_10.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.tab_2)
        self.label_16.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_10.addWidget(self.label_16, 1, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.tab_2)
        self.label_18.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_10.addWidget(self.label_18, 2, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.tab_2)
        self.label_20.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_10.addWidget(self.label_20, 3, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.tab_2)
        self.label_22.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_10.addWidget(self.label_22, 4, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.comboBox_4 = QtGui.QComboBox(self.tab_2)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.gridLayout_9.addWidget(self.comboBox_4, 0, 0, 1, 2)
        self.lineEdit_8 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.gridLayout_9.addWidget(self.lineEdit_8, 1, 0, 1, 1)
        self.toolButton_5 = QtGui.QToolButton(self.tab_2)
        self.toolButton_5.setObjectName(_fromUtf8("toolButton_5"))
        self.gridLayout_9.addWidget(self.toolButton_5, 1, 1, 1, 1)
        self.lineEdit_9 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.gridLayout_9.addWidget(self.lineEdit_9, 2, 0, 1, 1)
        self.toolButton_6 = QtGui.QToolButton(self.tab_2)
        self.toolButton_6.setObjectName(_fromUtf8("toolButton_6"))
        self.gridLayout_9.addWidget(self.toolButton_6, 2, 1, 1, 1)
        self.lineEdit_10 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.gridLayout_9.addWidget(self.lineEdit_10, 3, 0, 1, 1)
        self.toolButton_7 = QtGui.QToolButton(self.tab_2)
        self.toolButton_7.setObjectName(_fromUtf8("toolButton_7"))
        self.gridLayout_9.addWidget(self.toolButton_7, 3, 1, 1, 1)
        self.lineEdit_11 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.gridLayout_9.addWidget(self.lineEdit_11, 4, 0, 1, 2)
        self.gridLayout_11.addLayout(self.gridLayout_9, 0, 1, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.gridLayout_15 = QtGui.QGridLayout()
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.label_15 = QtGui.QLabel(self.tab_2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_15.addWidget(self.label_15, 0, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.tab_2)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_15.addWidget(self.label_17, 1, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.tab_2)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_15.addWidget(self.label_19, 2, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.tab_2)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_15.addWidget(self.label_21, 3, 0, 1, 1)
        self.label_23 = QtGui.QLabel(self.tab_2)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_15.addWidget(self.label_23, 4, 0, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_15, 0, 1, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_12, 0, 0, 1, 1)
        self.gridLayout_18 = QtGui.QGridLayout()
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.gridLayout_17 = QtGui.QGridLayout()
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.toolButton_8 = QtGui.QToolButton(self.tab_2)
        self.toolButton_8.setObjectName(_fromUtf8("toolButton_8"))
        self.gridLayout_17.addWidget(self.toolButton_8, 0, 0, 1, 1)
        self.toolButton_9 = QtGui.QToolButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_9.sizePolicy().hasHeightForWidth())
        self.toolButton_9.setSizePolicy(sizePolicy)
        self.toolButton_9.setObjectName(_fromUtf8("toolButton_9"))
        self.gridLayout_17.addWidget(self.toolButton_9, 1, 0, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_17, 0, 1, 2, 1)
        self.label_26 = QtGui.QLabel(self.tab_2)
        self.label_26.setText(_fromUtf8(""))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_18.addWidget(self.label_26, 0, 2, 2, 1)
        self.label_25 = QtGui.QLabel(self.tab_2)
        self.label_25.setText(_fromUtf8(""))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_18.addWidget(self.label_25, 0, 0, 2, 1)
        self.gridLayout_18.setColumnStretch(0, 1)
        self.gridLayout_18.setColumnStretch(1, 1)
        self.gridLayout_18.setColumnStretch(2, 6)
        self.gridLayout_19.addLayout(self.gridLayout_18, 1, 0, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_19, 0, 0, 1, 1)
        self.label_35 = QtGui.QLabel(self.tab_2)
        self.label_35.setText(_fromUtf8(""))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_16.addWidget(self.label_35, 1, 0, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_16, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_34 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_34.setObjectName(_fromUtf8("gridLayout_34"))
        self.gridLayout_33 = QtGui.QGridLayout()
        self.gridLayout_33.setObjectName(_fromUtf8("gridLayout_33"))
        self.gridLayout_32 = QtGui.QGridLayout()
        self.gridLayout_32.setObjectName(_fromUtf8("gridLayout_32"))
        self.gridLayout_31 = QtGui.QGridLayout()
        self.gridLayout_31.setObjectName(_fromUtf8("gridLayout_31"))
        self.gridLayout_26 = QtGui.QGridLayout()
        self.gridLayout_26.setObjectName(_fromUtf8("gridLayout_26"))
        self.label_45 = QtGui.QLabel(self.tab_3)
        self.label_45.setText(_fromUtf8(""))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_26.addWidget(self.label_45, 0, 0, 1, 1)
        self.label_46 = QtGui.QLabel(self.tab_3)
        self.label_46.setText(_fromUtf8(""))
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_26.addWidget(self.label_46, 1, 0, 1, 1)
        self.label_47 = QtGui.QLabel(self.tab_3)
        self.label_47.setText(_fromUtf8(""))
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_26.addWidget(self.label_47, 2, 0, 1, 1)
        self.gridLayout_31.addLayout(self.gridLayout_26, 0, 0, 1, 1)
        self.gridLayout_24 = QtGui.QGridLayout()
        self.gridLayout_24.setObjectName(_fromUtf8("gridLayout_24"))
        self.checkBox = QtGui.QCheckBox(self.tab_3)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_24.addWidget(self.checkBox, 0, 0, 1, 2)
        self.label_36 = QtGui.QLabel(self.tab_3)
        self.label_36.setText(_fromUtf8(""))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_24.addWidget(self.label_36, 1, 0, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.tab_3)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout_24.addWidget(self.checkBox_2, 1, 1, 1, 1)
        self.label_37 = QtGui.QLabel(self.tab_3)
        self.label_37.setText(_fromUtf8(""))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_24.addWidget(self.label_37, 2, 0, 1, 1)
        self.checkBox_3 = QtGui.QCheckBox(self.tab_3)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.gridLayout_24.addWidget(self.checkBox_3, 2, 1, 1, 1)
        self.gridLayout_24.setColumnStretch(0, 1)
        self.gridLayout_24.setColumnStretch(1, 10)
        self.gridLayout_31.addLayout(self.gridLayout_24, 0, 1, 1, 1)
        self.gridLayout_23 = QtGui.QGridLayout()
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.label_27 = QtGui.QLabel(self.tab_3)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_23.addWidget(self.label_27, 0, 0, 1, 1)
        self.label_28 = QtGui.QLabel(self.tab_3)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_23.addWidget(self.label_28, 1, 0, 1, 1)
        self.label_29 = QtGui.QLabel(self.tab_3)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_23.addWidget(self.label_29, 2, 0, 1, 1)
        self.gridLayout_31.addLayout(self.gridLayout_23, 0, 2, 1, 1)
        self.gridLayout_29 = QtGui.QGridLayout()
        self.gridLayout_29.setObjectName(_fromUtf8("gridLayout_29"))
        self.label_30 = QtGui.QLabel(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_29.addWidget(self.label_30, 0, 0, 1, 1)
        self.label_32 = QtGui.QLabel(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_29.addWidget(self.label_32, 1, 0, 1, 1)
        self.gridLayout_31.addLayout(self.gridLayout_29, 1, 0, 1, 1)
        self.gridLayout_28 = QtGui.QGridLayout()
        self.gridLayout_28.setObjectName(_fromUtf8("gridLayout_28"))
        self.lineEdit_12 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.gridLayout_28.addWidget(self.lineEdit_12, 0, 0, 1, 1)
        self.lineEdit_13 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.gridLayout_28.addWidget(self.lineEdit_13, 1, 0, 1, 1)
        self.gridLayout_31.addLayout(self.gridLayout_28, 1, 1, 1, 1)
        self.gridLayout_30 = QtGui.QGridLayout()
        self.gridLayout_30.setObjectName(_fromUtf8("gridLayout_30"))
        self.label_31 = QtGui.QLabel(self.tab_3)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_30.addWidget(self.label_31, 0, 0, 1, 1)
        self.label_33 = QtGui.QLabel(self.tab_3)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_30.addWidget(self.label_33, 1, 0, 1, 1)
        self.gridLayout_31.addLayout(self.gridLayout_30, 1, 2, 1, 1)
        self.gridLayout_32.addLayout(self.gridLayout_31, 0, 0, 1, 1)
        self.gridLayout_27 = QtGui.QGridLayout()
        self.gridLayout_27.setObjectName(_fromUtf8("gridLayout_27"))
        self.gridLayout_21 = QtGui.QGridLayout()
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.label_34 = QtGui.QLabel(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_21.addWidget(self.label_34, 0, 0, 1, 1)
        self.label_41 = QtGui.QLabel(self.tab_3)
        self.label_41.setText(_fromUtf8(""))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_21.addWidget(self.label_41, 1, 0, 1, 1)
        self.gridLayout_27.addLayout(self.gridLayout_21, 0, 0, 1, 1)
        self.gridLayout_22 = QtGui.QGridLayout()
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.label_39 = QtGui.QLabel(self.tab_3)
        self.label_39.setText(_fromUtf8(""))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_22.addWidget(self.label_39, 0, 0, 1, 1)
        self.listWidget = QtGui.QListWidget(self.tab_3)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.gridLayout_22.addWidget(self.listWidget, 1, 0, 1, 1)
        self.gridLayout_27.addLayout(self.gridLayout_22, 0, 1, 1, 1)
        self.gridLayout_25 = QtGui.QGridLayout()
        self.gridLayout_25.setObjectName(_fromUtf8("gridLayout_25"))
        self.label_42 = QtGui.QLabel(self.tab_3)
        self.label_42.setText(_fromUtf8(""))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_25.addWidget(self.label_42, 1, 0, 1, 1)
        self.label_44 = QtGui.QLabel(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_44.sizePolicy().hasHeightForWidth())
        self.label_44.setSizePolicy(sizePolicy)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_25.addWidget(self.label_44, 0, 0, 1, 1)
        self.gridLayout_27.addLayout(self.gridLayout_25, 0, 2, 1, 1)
        self.gridLayout_27.setColumnStretch(0, 1)
        self.gridLayout_27.setColumnStretch(1, 5)
        self.gridLayout_27.setColumnStretch(2, 6)
        self.gridLayout_32.addLayout(self.gridLayout_27, 1, 0, 1, 1)
        self.gridLayout_33.addLayout(self.gridLayout_32, 0, 0, 1, 1)
        self.label_43 = QtGui.QLabel(self.tab_3)
        self.label_43.setText(_fromUtf8(""))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_33.addWidget(self.label_43, 1, 0, 1, 1)
        self.gridLayout_34.addLayout(self.gridLayout_33, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.gridLayout_37.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.pushButton_2 = QtGui.QPushButton(Form)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_5.addWidget(self.pushButton_2, 0, 2, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(Form)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_5.addWidget(self.pushButton_3, 0, 3, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(Form)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_5.addWidget(self.pushButton_4, 0, 4, 1, 1)
        self.pushButton = QtGui.QPushButton(Form)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_5.addWidget(self.pushButton, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 1, 1, 1)
        self.gridLayout_5.setColumnStretch(0, 1)
        self.gridLayout_5.setColumnStretch(1, 1)
        self.gridLayout_37.addLayout(self.gridLayout_5, 2, 0, 1, 1)
        self.actionExport = QtGui.QAction(Form)
        self.actionExport.setCheckable(True)
        self.actionExport.setObjectName(_fromUtf8("actionExport"))

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.lineEdit, self.comboBox)
        Form.setTabOrder(self.comboBox, self.comboBox_2)
        Form.setTabOrder(self.comboBox_2, self.toolButton)
        Form.setTabOrder(self.toolButton, self.tabWidget)
        Form.setTabOrder(self.tabWidget, self.lineEdit_2)
        Form.setTabOrder(self.lineEdit_2, self.lineEdit_3)
        Form.setTabOrder(self.lineEdit_3, self.lineEdit_4)
        Form.setTabOrder(self.lineEdit_4, self.lineEdit_5)
        Form.setTabOrder(self.lineEdit_5, self.toolButton_2)
        Form.setTabOrder(self.toolButton_2, self.toolButton_3)
        Form.setTabOrder(self.toolButton_3, self.lineEdit_6)
        Form.setTabOrder(self.lineEdit_6, self.lineEdit_7)
        Form.setTabOrder(self.lineEdit_7, self.comboBox_3)
        Form.setTabOrder(self.comboBox_3, self.pushButton_2)
        Form.setTabOrder(self.pushButton_2, self.pushButton_3)
        Form.setTabOrder(self.pushButton_3, self.pushButton_4)
        Form.setTabOrder(self.pushButton_4, self.comboBox_4)
        Form.setTabOrder(self.comboBox_4, self.lineEdit_8)
        Form.setTabOrder(self.lineEdit_8, self.toolButton_5)
        Form.setTabOrder(self.toolButton_5, self.lineEdit_9)
        Form.setTabOrder(self.lineEdit_9, self.toolButton_6)
        Form.setTabOrder(self.toolButton_6, self.lineEdit_10)
        Form.setTabOrder(self.lineEdit_10, self.toolButton_7)
        Form.setTabOrder(self.toolButton_7, self.lineEdit_11)
        Form.setTabOrder(self.lineEdit_11, self.toolButton_8)
        Form.setTabOrder(self.toolButton_8, self.toolButton_9)
        Form.setTabOrder(self.toolButton_9, self.checkBox)
        Form.setTabOrder(self.checkBox, self.checkBox_2)
        Form.setTabOrder(self.checkBox_2, self.checkBox_3)
        Form.setTabOrder(self.checkBox_3, self.lineEdit_12)
        Form.setTabOrder(self.lineEdit_12, self.lineEdit_13)
        Form.setTabOrder(self.lineEdit_13, self.listWidget)
        Form.setTabOrder(self.listWidget, self.pushButton)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "RegistryDatabases", None))
        self.label.setText(_translate("Form", "Connection Name:", None))
        self.lineEdit.setText(_translate("Form", "connection", None))
        self.label_2.setText(_translate("Form", "Type a name for the connection.", None))
        self.label_3.setText(_translate("Form", "Connection Method:", None))
        self.comboBox.setItemText(0, _translate("Form", "Standard(TCP/IP)", None))
        self.comboBox.setItemText(1, _translate("Form", "Standard(TCP/IP) over SSH", None))
        self.comboBox.setItemText(2, _translate("Form", "Local Socket/Pipe", None))
        self.label_4.setText(_translate("Form", "Method to use to connect to the RDBMS.", None))
        self.label_52.setText(_translate("Form", "Connection Clients:", None))
        self.toolButton.setText(_translate("Form", "...", None))
        self.label_53.setText(_translate("Form", "Client to use to connect to the RDBMS.", None))
        self.label_8.setText(_translate("Form", "Username:", None))
        self.label_12.setText(_translate("Form", "ConnectAs:", None))
        self.label_5.setText(_translate("Form", "Hostname:", None))
        self.label_10.setText(_translate("Form", "Password:", None))
        self.label_40.setText(_translate("Form", "ServiceName:", None))
        self.label_49.setText(_translate("Form", "InstanceName:", None))
        self.toolButton_2.setText(_translate("Form", "Store in vault", None))
        self.toolButton_3.setText(_translate("Form", "Clear", None))
        self.lineEdit_5.setText(_translate("Form", "sys_pwd_123", None))
        self.lineEdit_4.setText(_translate("Form", "sys", None))
        self.label_6.setText(_translate("Form", "Port:", None))
        self.lineEdit_3.setText(_translate("Form", "1521", None))
        self.comboBox_3.setItemText(0, _translate("Form", "SYSDBA", None))
        self.comboBox_3.setItemText(1, _translate("Form", "SYSOPER", None))
        self.comboBox_3.setItemText(2, _translate("Form", "SYSASM", None))
        self.comboBox_3.setItemText(3, _translate("Form", "NORMAL", None))
        self.label_7.setText(_translate("Form", "Name or IP address of the server host - and TCP/IP port.", None))
        self.label_9.setText(_translate("Form", "Name of the user to connect with.", None))
        self.label_11.setText(_translate("Form", "The user\'s password,Will be requested later if it is not set.", None))
        self.label_13.setText(_translate("Form", "The schema to use as default schema.Leave blank to select to later.", None))
        self.label_48.setText(_translate("Form", "The ServiceName,will be requested later if it is not set.", None))
        self.label_50.setText(_translate("Form", "The SID,will be requested later if it is not set.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Parameters", None))
        self.label_14.setText(_translate("Form", "Use SSL", None))
        self.label_16.setText(_translate("Form", "SSL Key File:", None))
        self.label_18.setText(_translate("Form", "SSL CERT File:", None))
        self.label_20.setText(_translate("Form", "SSL CA File:", None))
        self.label_22.setText(_translate("Form", "SSL Cipher:", None))
        self.comboBox_4.setItemText(0, _translate("Form", "No", None))
        self.comboBox_4.setItemText(1, _translate("Form", "If available", None))
        self.comboBox_4.setItemText(2, _translate("Form", "Require", None))
        self.comboBox_4.setItemText(3, _translate("Form", "Require and Verify CA", None))
        self.comboBox_4.setItemText(4, _translate("Form", "Require and Verify Identity", None))
        self.toolButton_5.setText(_translate("Form", "...", None))
        self.toolButton_6.setText(_translate("Form", "...", None))
        self.toolButton_7.setText(_translate("Form", "...", None))
        self.label_15.setText(_translate("Form", "Turns on SSL encryption.Connection will fail if SSL is not available. ", None))
        self.label_17.setText(_translate("Form", "Path to Client Key file for SSL.", None))
        self.label_19.setText(_translate("Form", "Path to Client Certificate file for SSL.", None))
        self.label_21.setText(_translate("Form", "Path to Certificate Authority file for SSL.", None))
        self.label_23.setText(_translate("Form", "Optional:separated list of permissible ciphers to use for SSL encryption.", None))
        self.toolButton_8.setText(_translate("Form", "SSL Wizard ...", None))
        self.toolButton_9.setText(_translate("Form", "Files", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "SSL", None))
        self.checkBox.setText(_translate("Form", "Use compression protocol", None))
        self.checkBox_2.setText(_translate("Form", "Use ANSI quotes to quote identifiers", None))
        self.checkBox_3.setText(_translate("Form", "Enable Cleartext Authentication Plugin", None))
        self.label_27.setText(_translate("Form", "Select this option for WAN connections.", None))
        self.label_28.setText(_translate("Form", "If enabled this option overwrites the serverside settings.", None))
        self.label_29.setText(_translate("Form", "Send user password in cleartext.Required for some authentication methods.", None))
        self.label_30.setText(_translate("Form", "Timeout:", None))
        self.label_32.setText(_translate("Form", "SQL_MODE:", None))
        self.lineEdit_12.setText(_translate("Form", "60", None))
        self.label_31.setText(_translate("Form", "Maximum time to wait before a connection is aborted.", None))
        self.label_33.setText(_translate("Form", "Override the default SQL_MODE used by the server.", None))
        self.label_34.setText(_translate("Form", "Others:", None))
        self.label_44.setText(_translate("Form", "Other options for Connector/C++ as option=value pairs,one per line.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Advanced", None))
        self.pushButton_2.setText(_translate("Form", "Test Connection", None))
        self.pushButton_3.setText(_translate("Form", "Registry", None))
        self.pushButton_4.setText(_translate("Form", "Cancel", None))
        self.pushButton.setText(_translate("Form", "Configure Server Management ...", None))
        self.actionExport.setText(_translate("Form", "Export", None))
        self.actionExport.setToolTip(_translate("Form", "Export", None))
        self.actionExport.setShortcut(_translate("Form", "Ctrl+Alt+E", None))

