# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'su_module_index.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("ooopic_1569555377.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.treeWidget = QtGui.QTreeWidget(self.groupBox_3)
        self.treeWidget.setHeaderHidden(True)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.treeWidget.headerItem().setFont(0, font)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        self.gridLayout_7.addWidget(self.treeWidget, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.label_100 = QtGui.QLabel(self.groupBox_2)
        self.label_100.setObjectName(_fromUtf8("label_100"))
        self.gridLayout_12.addWidget(self.label_100, 0, 0, 1, 1)
        self.label_102 = QtGui.QLabel(self.groupBox_2)
        self.label_102.setObjectName(_fromUtf8("label_102"))
        self.gridLayout_12.addWidget(self.label_102, 2, 0, 1, 1)
        self.label_103 = QtGui.QLabel(self.groupBox_2)
        self.label_103.setObjectName(_fromUtf8("label_103"))
        self.gridLayout_12.addWidget(self.label_103, 3, 0, 1, 1)
        self.label_104 = QtGui.QLabel(self.groupBox_2)
        self.label_104.setObjectName(_fromUtf8("label_104"))
        self.gridLayout_12.addWidget(self.label_104, 4, 0, 1, 1)
        self.label_105 = QtGui.QLabel(self.groupBox_2)
        self.label_105.setObjectName(_fromUtf8("label_105"))
        self.gridLayout_12.addWidget(self.label_105, 5, 0, 1, 1)
        self.label_101 = QtGui.QLabel(self.groupBox_2)
        self.label_101.setObjectName(_fromUtf8("label_101"))
        self.gridLayout_12.addWidget(self.label_101, 1, 0, 1, 1)
        self.label_106 = QtGui.QLabel(self.groupBox_2)
        self.label_106.setObjectName(_fromUtf8("label_106"))
        self.gridLayout_12.addWidget(self.label_106, 6, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_12, 0, 0, 1, 1)
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_11.addWidget(self.label_8, 5, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setText(_fromUtf8(""))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_11.addWidget(self.label_7, 4, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_11.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_11.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_11.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_11.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setText(_fromUtf8(""))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_11.addWidget(self.label_9, 6, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_11, 0, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_9, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.gridLayout_3.setRowStretch(0, 1)
        self.gridLayout_10.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.stackedWidget = QtGui.QStackedWidget(self.groupBox)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtGui.QWidget()
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtGui.QWidget()
        self.page_6.setObjectName(_fromUtf8("page_6"))
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtGui.QWidget()
        self.page_7.setObjectName(_fromUtf8("page_7"))
        self.stackedWidget.addWidget(self.page_7)
        self.page_8 = QtGui.QWidget()
        self.page_8.setObjectName(_fromUtf8("page_8"))
        self.stackedWidget.addWidget(self.page_8)
        self.page_9 = QtGui.QWidget()
        self.page_9.setObjectName(_fromUtf8("page_9"))
        self.stackedWidget.addWidget(self.page_9)
        self.page_10 = QtGui.QWidget()
        self.page_10.setObjectName(_fromUtf8("page_10"))
        self.gridLayout_5 = QtGui.QGridLayout(self.page_10)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pushButton = QtGui.QPushButton(self.page_10)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_2.addWidget(self.pushButton, 4, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 4, 0, 1, 1)
        self.tableWidget = QtGui.QTableWidget(self.page_10)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.gridLayout_2.addWidget(self.tableWidget, 3, 0, 1, 2)
        self.gridLayout_13 = QtGui.QGridLayout()
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.gridLayout_14 = QtGui.QGridLayout()
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.label_13 = QtGui.QLabel(self.page_10)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_14.addWidget(self.label_13, 0, 0, 1, 1)
        self.comboBox_2 = QtGui.QComboBox(self.page_10)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.gridLayout_14.addWidget(self.comboBox_2, 0, 1, 1, 1)
        self.gridLayout_14.setColumnStretch(1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_14, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem1, 0, 1, 1, 1)
        self.gridLayout_15 = QtGui.QGridLayout()
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.label_14 = QtGui.QLabel(self.page_10)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_15.addWidget(self.label_14, 0, 0, 1, 1)
        self.comboBox_3 = QtGui.QComboBox(self.page_10)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.gridLayout_15.addWidget(self.comboBox_3, 0, 1, 1, 1)
        self.gridLayout_15.setColumnStretch(1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_15, 0, 2, 1, 1)
        self.gridLayout_13.setColumnStretch(0, 1)
        self.gridLayout_13.setColumnStretch(2, 1)
        self.gridLayout_2.addLayout(self.gridLayout_13, 2, 0, 1, 2)
        self.label_2 = QtGui.QLabel(self.page_10)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 2)
        self.line = QtGui.QFrame(self.page_10)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 2)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_10)
        self.page_11 = QtGui.QWidget()
        self.page_11.setObjectName(_fromUtf8("page_11"))
        self.gridLayout_18 = QtGui.QGridLayout(self.page_11)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.gridLayout_17 = QtGui.QGridLayout()
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.tableWidget_2 = QtGui.QTableWidget(self.page_11)
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.tableWidget_2.horizontalHeader().setVisible(True)
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_2.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.tableWidget_2.verticalHeader().setCascadingSectionResizes(False)
        self.gridLayout_17.addWidget(self.tableWidget_2, 2, 0, 1, 1)
        self.gridLayout_16 = QtGui.QGridLayout()
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem2, 0, 0, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.page_11)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_16.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_16, 3, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.page_11)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_17.addWidget(self.label_19, 0, 0, 1, 1)
        self.line_3 = QtGui.QFrame(self.page_11)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_17.addWidget(self.line_3, 1, 0, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_17, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_11)
        self.gridLayout_4.addWidget(self.stackedWidget, 2, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.groupBox)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_4.addWidget(self.line_2, 1, 0, 1, 1)
        self.gridLayout_20 = QtGui.QGridLayout()
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.comboBox = QtGui.QComboBox(self.groupBox)
        self.comboBox.setFrame(True)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.gridLayout_20.addWidget(self.comboBox, 0, 0, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_20.addWidget(self.label, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_20, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox, 0, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_6, 0, 1, 1, 1)
        self.gridLayout_10.setColumnStretch(0, 1)
        self.gridLayout_10.setColumnStretch(1, 3)
        self.gridLayout.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(10)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.treeWidget, self.comboBox)
        MainWindow.setTabOrder(self.comboBox, self.comboBox_2)
        MainWindow.setTabOrder(self.comboBox_2, self.comboBox_3)
        MainWindow.setTabOrder(self.comboBox_3, self.tableWidget)
        MainWindow.setTabOrder(self.tableWidget, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.tableWidget_2)
        MainWindow.setTabOrder(self.tableWidget_2, self.pushButton_2)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "ServerUtilities", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Navigator", None))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Navigator", None))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "Monitor", None))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "Server Status", None))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "Users and Privileges", None))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "System Variables", None))
        self.treeWidget.topLevelItem(0).child(3).setText(0, _translate("MainWindow", "Report Export", None))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "Installation", None))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "Oracle Installation", None))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "Mysq Installation", None))
        self.treeWidget.topLevelItem(1).child(2).setText(0, _translate("MainWindow", "PostgreSQL Installation", None))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "Maintenance", None))
        self.treeWidget.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "Oracle DDL Authorization", None))
        self.treeWidget.topLevelItem(2).child(1).setText(0, _translate("MainWindow", "Database Increment", None))
        self.treeWidget.topLevelItem(2).child(2).setText(0, _translate("MainWindow", "Oracle DataGuard", None))
        self.treeWidget.topLevelItem(2).child(3).setText(0, _translate("MainWindow", "ASM DiskGroup", None))
        self.treeWidget.topLevelItem(3).setText(0, _translate("MainWindow", "Inspection", None))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox_2.setTitle(_translate("MainWindow", "Summary", None))
        self.label_100.setText(_translate("MainWindow", "Server:", None))
        self.label_102.setText(_translate("MainWindow", "Instance：", None))
        self.label_103.setText(_translate("MainWindow", "dbName:", None))
        self.label_104.setText(_translate("MainWindow", "dbUname:", None))
        self.label_105.setText(_translate("MainWindow", "OpenMode:", None))
        self.label_101.setText(_translate("MainWindow", "Version:", None))
        self.label_106.setText(_translate("MainWindow", "Platform:", None))
        self.groupBox.setTitle(_translate("MainWindow", "Connection", None))
        self.pushButton.setText(_translate("MainWindow", "Verify DataGuard", None))
        self.label_13.setText(_translate("MainWindow", "Primary:", None))
        self.label_14.setText(_translate("MainWindow", "Standby:", None))
        self.label_2.setText(_translate("MainWindow", "DG synchronization status monitoring", None))
        self.pushButton_2.setText(_translate("MainWindow", "Verify", None))
        self.label_19.setText(_translate("MainWindow", "Oracle ASM DiskGoups Status", None))
        self.label.setText(_translate("MainWindow", "Select the IP of target server.", None))

